OTP_EXPIRY_MINUTES     = 5
MAX_ATTEMPTS           = 3
MAX_RESEND_ATTEMPTS    = 3
BLOCK_DURATION_HOURS   = 24
MAX_DEVICES            = 3
MAX_VERIFY_ATTEMPTS    = 3
OTP_EXPIRY_SECONDS     = OTP_EXPIRY_MINUTES * 60
OTP_BLOCK_HOURS        =24
