from enum import Enum


class LoanStatus(str, Enum):

    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    CREDIT_CHECK = "CREDIT_CHECK"
    LENDER_REVIEW = "LENDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    AGREEMENT_PENDING = "AGREEMENT_PENDING"
    DISBURSEMENT_INITIATED = "DISBURSEMENT_INITIATED"
    DISBURSED = "DISBURSED"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class NotificationType(str, Enum):

    STATUS_UPDATE = "STATUS_UPDATE"
    DOCUMENT = "DOCUMENT"
    NBFC = "NBFC"


class NotificationChannel(str, Enum):

    IN_APP = "IN_APP"
    SMS = "SMS"